### ISSUE TITLE
state of this crate?

### ISSUE THREAD

**Issue by HaoboGu** [ch32-rs/ch58x-hal#5]
hello! I want to use the crate for an experimental project, but not sure the state of the crate. I'm wondering is there a roadmap for this crate, so that everyone can know the current state of this project？

**Comment by HaoboGu** [comment]
I can also contribute something if there's a need :)

**Comment by andelf** [comment]
Thanks. This project is currently maintained and won't be abandoned. 
I work on this project(and the ch32-rs org) in my spare time. 

- ch58x-hal is at an early alpha stage with common tasks available(at least BLE works)
  - This crate is not production ready and all the APIs will be changed
  - This crate is OK for any hobby project and experiment with Rust Embedded
- Since CH57x/CH58x/CH59x shares almost the same peripherals, this will also be the template of ch57x-hal/ch59x-hal
  - They might be merged into one crate
  - ch58x-hal might be directly renamed to ch5xble-hal or something similar

Any contribution is welcomed.

**Comment by HaoboGu** [comment]
that's cool! How can I involve myself contributing the project? Is there a contribution guide or something like it?
